# Generated by Django 6.0.2 on 2026-03-04 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusflow', '0001_fix_tabla_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='completada',
            field=models.BooleanField(default=False, help_text='Casilla para marcar la tarea como completa'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='nombre',
            field=models.CharField(help_text='El nombre descriptivo de la tarea', max_length=100),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='ID de la tarea padre, si esto es tarea padre se deja vacio', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtareas', to='focusflow.tarea'),
        ),
    ]
