# Generated by Django 6.0.2 on 2026-03-07 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusflow', '0002_alter_tarea_completada_alter_tarea_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='carga_mental',
            field=models.CharField(blank=True, help_text='Carga mental (1-5)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='descripcion',
            field=models.CharField(blank=True, help_text='La descripción de la tarea', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, help_text='Formato: AAAA-MM-DD HH:MM:SS', null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='ID de la tarea padre', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtareas', to='focusflow.tarea'),
        ),
    ]
