# Generated by Django 6.0.2 on 2026-03-07 02:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusflow', '0003_tarea_carga_mental_tarea_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de creacion de la tarea'),
        ),
    ]
