# Generated by Django 6.0.2 on 2026-03-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusflow', '0004_tarea_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='curso',
            field=models.CharField(blank=True, help_text='Casilla para el curso', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='tipo_tarea',
            field=models.CharField(choices=[('EX', 'Examen'), ('QU', 'Quiz'), ('TA', 'Taller'), ('PR', 'Proyecto'), ('OT', 'Otro')], default='OT', help_text='Selecciona el tipo de tarea', max_length=2),
        ),
    ]
