# Generated by Django 6.0.2 on 2026-03-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusflow', '0005_tarea_curso_tarea_tipo_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='curso',
            field=models.CharField(default='Sin definir', help_text='Casilla para el curso', max_length=255),
        ),
    ]
